version: "3"

services:
  flask:
    build: .
    container_name: flask
    networks:
      - front
      - back
    links:
      - mongo

  mongo:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=portfolioDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - back
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - front
    links:
      - flask

volumes:
  mongo-data:

networks:
  front:
  back: