version: "3"

services:
  flask:
    build: .
    container_name: flask
    networks:
      - front
      - back
    links: #waits for DB before creating the application
      - mongo

  mongo:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=portfolioDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - back
    volumes:
      - mongo-data:/data/db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - front
    links:
      - flask #waits for application before creating the Nginx

volumes:
  mongo-data:

networks:
  front:
  back: